### ISSUE TITLE
Tracking piece movements

### ISSUE THREAD

**Issue by 3ygun** [ChessCV/chess#2]
# Goal
Piece movement tracking of `chess.com` board

# Algorithms
Color histogram before and after each move is performed?

# Parts
- [ ] Detect board state change
  - Start with manual input for board state change?
- [ ] What is `moved from` position?
- [ ] What is `moved to` position?
