### ISSUE TITLE
Tracking Piece Movements

### ISSUE THREAD

**Issue by 3ygun** [ChessCV/chess#7]
# Goals
Tracking of piece movements.

# Algorithms
- Mean shift tracking to determine where pieces are and where they've ended up?

# Notes
- Allow `space-bar` trigger to notate move. Additionally, justifies the timer

# Parts
- [x] Detect when a move is made
- [x] What is the `moved from` position
- [x] What is the `moved to` position

**Comment by TheMysteriousMrRe** [comment]
Works with giving it two images one of the before move and one of the after move
